// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkzftifrtvsjpvxlnztl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpremZ0aWZydHZzanB2eGxuenRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDg4ODEsImV4cCI6MjA1NzM4NDg4MX0.dzg4xP8m7kIYsAuxpUHrHg16v0GXI1dgtGQbKmxWYjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);